### ISSUE TITLE
Application-Already-Deployed

### ISSUE THREAD

**Issue by stephnna** [stephnna/portfolio#11]
Hi code reviewer,
Already, I have deployed my application now hence, I have to open this issue with a link to its online version.

The deployment was straightforward; I used GitHub pages to achieve it..

Here is the link: https://stephnna.github.io/portfolio/. Kindly review as necessary.

Thanks

**Comment by codepantha** [comment]
Hi @stephnna 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

### Optional
- Kindly update your README with a link to the online version of your portfolio so that people can easily see your awesome work 👍 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stephnna** [comment]
Yeah, I have done so, thanks!
